### ISSUE TITLE
AutoSDK folder must be reserved for lifetime of build process

### ISSUE THREAD

**Issue by hach-que** [RedpointGames/uet#17]
UBT can try to write files into the AutoSDK folder, so we need to use reservations for this and have multiple copies of it in order for things to work correctly:

```
[info] [Compile UnrealGame Win64 Shipping] System.IO.IOException: The process cannot access the file 'C:\ProgramData\UET\SDKs\AutoSDK-1fdy1i6443dys_7bwaf_\HostWin64\Android\CurrentlyInstalled.txt' because it is being used by another process.
[info] [Compile UnrealGame Win64 Shipping]    at Microsoft.Win32.SafeHandles.SafeFileHandle.CreateFile(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options)
[info] [Compile UnrealGame Win64 Shipping]    at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize)
[info] [Compile UnrealGame Win64 Shipping]    at System.IO.Strategies.OSFileStreamStrategy..ctor(String path, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize)
[info] [Compile UnrealGame Win64 Shipping]    at System.IO.Strategies.FileStreamHelpers.ChooseStrategyCore(String path, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize)
[info] [Compile UnrealGame Win64 Shipping]    at System.IO.Strategies.FileStreamHelpers.ChooseStrategy(FileStream fileStream, String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, Int64 preallocationSize)
[info] [Compile UnrealGame Win64 Shipping]    at System.IO.StreamWriter.ValidateArgsAndOpenPath(String path, Boolean append, Encoding encoding, Int32 bufferSize)
[info] [Compile UnrealGame Win64 Shipping]    at System.IO.File.CreateText(String path)
[info] [Compile UnrealGame Win64 Shipping]    at EpicGames.Core.UEBuildPlatformSDK.SetupManualSDK() in C:\UES\15r39ja86.ip4j-001\Engine\Source\Programs\Shared\EpicGames.Build\UEBuildPlatformSDK.cs:line 1239
[info] [Compile UnrealGame Win64 Shipping]    at EpicGames.Core.UEBuildPlatformSDK.ManageAndValidateSDK() in C:\UES\15r39ja86.ip4j-001\Engine\Source\Programs\Shared\EpicGames.Build\UEBuildPlatformSDK.cs:line 1896
[info] [Compile UnrealGame Win64 Shipping]    at UnrealBuildTool.UEBuildPlatform..ctor(UnrealTargetPlatform InPlatform, UEBuildPlatformSDK SDK, UnrealArchitectureConfig ArchitectureConfig, ILogger InLogger) in C:\UES\15r39ja86.ip4j-001\Engine\Source\Programs\UnrealBuildTool\Configuration\UEBuildPlatform.cs:line 248
[info] [Compile UnrealGame Win64 Shipping]    at UnrealBuildTool.AndroidPlatform..ctor(UnrealTargetPlatform InTargetPlatform, UEBuildPlatformSDK InSDK, ILogger InLogger) in C:\UES\15r39ja86.ip4j-001\Engine\Source\Programs\UnrealBuildTool\Platform\Android\UEBuildAndroid.cs:line 167
[info] [Compile UnrealGame Win64 Shipping]    at UnrealBuildTool.AndroidPlatform..ctor(AndroidPlatformSDK InSDK, ILogger InLogger) in C:\UES\15r39ja86.ip4j-001\Engine\Source\Programs\UnrealBuildTool\Platform\Android\UEBuildAndroid.cs:line 172
[info] [Compile UnrealGame Win64 Shipping]    at UnrealBuildTool.AndroidPlatformFactory.RegisterBuildPlatforms(ILogger Logger) in C:\UES\15r39ja86.ip4j-001\Engine\Source\Programs\UnrealBuildTool\Platform\Android\UEBuildAndroid.cs:line 608
[info] [Compile UnrealGame Win64 Shipping]    at UnrealBuildTool.UEBuildPlatform.RegisterPlatforms(Boolean bIncludeNonInstalledPlatforms, Boolean bHostPlatformOnly, String[] ArgumentsForPerPlatform, Boolean bArgumentsAreForUBT, ILogger Logger) in C:\UES\15r39ja86.ip4j-001\Engine\Source\Programs\UnrealBuildTool\Configuration\UEBuildPlatform.cs:line 395
[info] [Compile UnrealGame Win64 Shipping]    at UnrealBuildTool.UEBuildPlatform.RegisterPlatforms(Boolean bIncludeNonInstalledPlatforms, Boolean bHostPlatformOnly, String[] ArgumentsForPerPlatform, ILogger Logger) in C:\UES\15r39ja86.ip4j-001\Engine\Source\Programs\UnrealBuildTool\Configuration\UEBuildPlatform.cs:line 351
[info] [Compile UnrealGame Win64 Shipping]    at UnrealBuildTool.PlatformExports.Initialize(String[] CommandLineArgs, ILogger Logger) in C:\UES\15r39ja86.ip4j-001\Engine\Source\Programs\UnrealBuildTool\System\PlatformExports.cs:line 158
[info] [Compile UnrealGame Win64 Shipping]    at AutomationTool.Automation.ProcessAsync(ParsedCommandLine AutomationToolCommandLine, StartupTraceListener StartupListener, HashSet`1 ScriptModuleAssemblies) in C:\UES\15r39ja86.ip4j-001\Engine\Source\Programs\AutomationTool\AutomationUtils\Automation.cs:line 119
[info] [Compile UnrealGame Win64 Shipping] (see C:\Windows\system32\config\systemprofile\AppData\Roaming\Unreal Engine\AutomationTool\Logs\C+UES+15r39ja86.ip4j-001\Log.txt for full exception trace)
```

**Comment by hach-que** [comment]
I realised we can't have multiple AutoSDK folders because this would cause things like include paths to change between builds, which would result in unnecessary rebuilds.
