### ISSUE TITLE
Need 7z.dll inside : Failed to extract NSIS installer with 7-Zip

### ISSUE THREAD

**Issue by wangjieest** [RedpointGames/uet#59]
[info] The following platforms will have their SDKs configured:

[2024-11-27T02:14:55.131Z] [info]  - Windows

[2024-11-27T02:14:55.131Z] [info]  - Android

[2024-11-27T02:14:55.131Z] [info]  - Linux

[2024-11-27T02:14:55.131Z] [info] Requesting SDK for platform Windows...

[2024-11-27T02:14:55.131Z] [info] Requesting SDK for platform Android...

[2024-11-27T02:14:55.131Z] [info] Requesting SDK for platform Linux...

[2024-11-27T02:14:55.131Z] [info] Downloading Linux cross-compile toolchain v22_clang-16.0.6-centos7...

[2024-11-27T02:15:00.709Z]                 progress:     59.73 % (    504 /    844) MB, 97.04 MB/s, 0:03 to go

[2024-11-27T02:15:03.420Z] [info] Extracting Linux cross-compile toolchain v22_clang-16.0.6-centos7...

[2024-11-27T02:15:03.420Z] 

[2024-11-27T02:15:03.420Z] 7-Zip 22.01 (x64) : Copyright (c) 1999-2022 Igor Pavlov : 2022-07-15

[2024-11-27T02:15:03.420Z] 

[2024-11-27T02:15:03.420Z] 

[2024-11-27T02:15:03.420Z] Codec Load Error: C:\ProgramData\UET\SDKs\Linux-v22_clang-16.0.6-centos7-tmp-89192\7z.dll : The specified module could not be found.

[2024-11-27T02:15:03.420Z] 

[2024-11-27T02:15:03.420Z] Scanning the drive for archives:

[2024-11-27T02:15:03.420Z] 1 file, 886036624 bytes (845 MiB)

[2024-11-27T02:15:03.420Z] 

[2024-11-27T02:15:03.420Z] Extracting archive: ..\toolchainextract.exe

[2024-11-27T02:15:03.420Z] ERROR: ..\toolchainextract.exe

[2024-11-27T02:15:03.420Z] Cannot open the file as archive

[2024-11-27T02:15:03.420Z] 

[2024-11-27T02:15:03.420Z] 

[2024-11-27T02:15:03.420Z] Can't open as archive: 1

[2024-11-27T02:15:03.420Z] Files: 0

[2024-11-27T02:15:03.420Z] Size:       0

[2024-11-27T02:15:03.420Z] Compressed: 0

[2024-11-27T02:15:03.420Z] [fail] Uncaught exception during command execution: Redpoint.Uet.SdkManagement.SdkSetupPackageGenerationFailedException: Failed to extract NSIS installer with 7-Zip.    at Redpoint.Uet.SdkManagement.LinuxSdkSetup.GenerateSdkPackage(String, String, CancellationToken)    at Redpoint.Uet.SdkManagement.DefaultLocalSdkManager.SetupEnvironmentForSdkSetups(String, String, ISet`1, CancellationToken)    at Redpoint.Uet.SdkManagement.DefaultLocalSdkManager.SetupEnvironmentForSdkSetups(String, String, ISet`1, CancellationToken)    at UET.Commands.InstallSdks.InstallSdksCommand.InstallSdksCommandInstance.ExecuteAsync(InvocationContext)    at UET.Commands.CommandExtensions.<>c__DisplayClass6_0`1.<<AddCommonHandler>b__0>d.MoveNext() Redpoint.Uet.SdkManagement.SdkSetupPackageGenerationFailedException: Failed to extract NSIS installer with 7-Zip.    at Redpoint.Uet.SdkManagement.LinuxSdkSetup.GenerateSdkPackage(String, String, CancellationToken)    at Redpoint.Uet.SdkManagement.DefaultLocalSdkManager.SetupEnvironmentForSdkSetups(String, String, ISet`1, CancellationToken)    at Redpoint.Uet.SdkManagement.DefaultLocalSdkManager.SetupEnvironmentForSdkSetups(String, String, ISet`1, CancellationToken)    at UET.Commands.InstallSdks.InstallSdksCommand.InstallSdksCommandInstance.ExecuteAsync(InvocationContext)    at UET.Commands.CommandExtensions.<>c__DisplayClass6_0`1.<<AddCommonHandler>b__0>d.MoveNext()

[2024-11-27T02:15:03.420Z] Unhandled exception: Redpoint.Uet.SdkManagement.SdkSetupPackageGenerationFailedException: Failed to extract NSIS installer with 7-Zip.

[2024-11-27T02:15:03.420Z]    at Redpoint.Uet.SdkManagement.LinuxSdkSetup.GenerateSdkPackage(String, String, CancellationToken)

[2024-11-27T02:15:03.420Z]    at Redpoint.Uet.SdkManagement.DefaultLocalSdkManager.SetupEnvironmentForSdkSetups(String, String, ISet`1, CancellationToken)

[2024-11-27T02:15:03.420Z]    at Redpoint.Uet.SdkManagement.DefaultLocalSdkManager.SetupEnvironmentForSdkSetups(String, String, ISet`1, CancellationToken)

[2024-11-27T02:15:03.420Z]    at UET.Commands.InstallSdks.InstallSdksCommand.InstallSdksCommandInstance.ExecuteAsync(InvocationContext)

[2024-11-27T02:15:03.420Z]    at UET.Commands.CommandExtensions.<>c__DisplayClass6_0`1.<<AddCommonHandler>b__0>d.MoveNext()

[2024-11-27T02:15:03.420Z] --- End of stack trace from previous location ---

[2024-11-27T02:15:03.420Z]    at UET.Commands.CommandExtensions.<>c__DisplayClass6_0`1.<<AddCommonHandler>b__0>d.MoveNext()

[2024-11-27T02:15:03.420Z] --- End of stack trace from previous location ---

[2024-11-27T02:15:03.420Z]    at UET.Commands.CommandExtensions.<>c__DisplayClass6_0`1.<<AddCommonHandler>b__0>d.MoveNext()

[2024-11-27T02:15:03.420Z] --- End of stack trace from previous location ---

[2024-11-27T02:15:03.420Z]    at System.CommandLine.Invocation.AnonymousCommandHandler.InvokeAsync(InvocationContext)

[2024-11-27T02:15:03.420Z]    at System.CommandLine.Invocation.InvocationPipeline.<>c__DisplayClass4_0.<<BuildInvocationChain>b__0>d.MoveNext()

[2024-11-27T02:15:03.420Z] --- End of stack trace from previous location ---

[2024-11-27T02:15:03.420Z]    at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass17_0.<<UseParseErrorReporting>b__0>d.MoveNext()

[2024-11-27T02:15:03.420Z] --- End of stack trace from previous location ---

[2024-11-27T02:15:03.420Z]    at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass12_0.<<UseHelp>b__0>d.MoveNext()

[2024-11-27T02:15:03.420Z] --- End of stack trace from previous location ---

[2024-11-27T02:15:03.420Z]    at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass22_0.<<UseVersionOption>b__0>d.MoveNext()

[2024-11-27T02:15:03.420Z] --- End of stack trace from previous location ---

[2024-11-27T02:15:03.420Z]    at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass19_0.<<UseTypoCorrections>b__0>d.MoveNext()

[2024-11-27T02:15:03.420Z] --- End of stack trace from previous location ---

[2024-11-27T02:15:03.420Z]    at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c.<<UseSuggestDirective>b__18_0>d.MoveNext()

[2024-11-27T02:15:03.420Z] --- End of stack trace from previous location ---

[2024-11-27T02:15:03.420Z]    at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass16_0.<<UseParseDirective>b__0>d.MoveNext()

[2024-11-27T02:15:03.420Z] --- End of stack trace from previous location ---

[2024-11-27T02:15:03.420Z]    at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c.<<RegisterWithDotnetSuggest>b__5_0>d.MoveNext()

[2024-11-27T02:15:03.420Z] --- End of stack trace from previous location ---

[2024-11-27T02:15:03.420Z]    at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass8_0.<<UseExceptionHandler>b__0>d.MoveNext()

script returned exit code 1

**Comment by hach-que** [comment]
Hmm that's pretty weird that I haven't seen it on any of my machines. Though I do have 7-zip installed generally, so that might be why.

We should probably just install 7-zip on demand via WinGet rather than trying to ship the binary inside UET.
